services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "${S3_PORT:-9004}:9000"   # API
      - "9005:9001"               # Painel (Console)
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_API_CORS_ALLOW_ORIGIN: "*"
    volumes:
      - s3_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  createbuckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      S3_BUCKET: ${S3_BUCKET:-chatwoot}
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -e
        until mc alias set minio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do
          echo "Waiting for MinIO..."
          sleep 2
        done

        # Bucket principal definido no .env
        mc mb --ignore-existing minio/${S3_BUCKET:-chatwoot}
        mc mb --ignore-existing minio/${S3_BUCKET:-chatwoot}/public
        mc anonymous set public minio/${S3_BUCKET:-chatwoot}/public


        exit 0
    networks:
      - app_network

volumes:
  s3_data:
